name: app-ci-pipeline
env: 
   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
   AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
on: 
   push: 
      branches:
         - master
      paths:
         - 'Dockerfile'
         - '.github/workflows/**'
         - '.deploy/**'
         - 'src/**'
   pull_request:
      branches:
         - master